bazel-contrib/publish-to-bcr

deployment/README.md, deployment/environments/dev/main.tf, deployment/environments/dev/variables.tf, deployment/environments/prod/main.tf, deployment/environments/prod/variables.tf, deployment/modules/webhook/main.tf, deployment/modules/webhook/variables.tf, package.json, src/application/cloudfunction/github-webhook-entrypoint.ts, src/application/notifications.ts, src/application/release-event-handler.ts, src/domain/find-registry-fork.spec.ts, src/domain/find-registry-fork.ts, src/domain/publish-entry.spec.ts, src/domain/publish-entry.ts, src/domain/user.ts, src/infrastructure/email.ts, src/infrastructure/github.ts, yarn.lock
This adds the capability to send emails to the releaser. Notifications that are actually helpful will go into another PR.
=> feat: send emails on success/failure

README.md, templates/README.md
Reads better in GitHub as you can see the files alongside the readme.
=> docs: minor docs fixes

src/domain/create-entry.spec.ts, src/domain/create-entry.ts
=> fix: add a trailing newline to a stamped source.json file

src/application/notifications.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/release-hash.ts, src/infrastructure/github.ts
Commit 1: Gives me better visibility into what error messages we're sending to users.
Commit 2: Fixes https://github.com/bazel-contrib/publish-to-bcr/issues/16
Commit 3: Better error email when user forgot to install to fork.
=> Various fixes

src/domain/ruleset-repository.spec.ts, src/domain/ruleset-repository.ts, src/test/mock-template-files.ts
Fixes:
* https://github.com/bazel-contrib/publish-to-bcr/issues/26
* https://github.com/bazel-contrib/publish-to-bcr/issues/24
=> Support empty strip_prefix and be flexible on config yaml extension

src/domain/create-entry.ts, src/infrastructure/github.ts
Fixes https://github.com/bazel-contrib/publish-to-bcr/issues/39.
=> fix: fix a bug where users were not warned when app not installed to fork

deployment/environments/dev/main.tf, deployment/environments/dev/variables.tf, deployment/environments/prod/main.tf, deployment/environments/prod/variables.tf, deployment/modules/webhook/main.tf, deployment/modules/webhook/variables.tf, src/application/notifications.ts
Addresses https://github.com/bazel-contrib/publish-to-bcr/issues/38.
=> chore: notify me when users encounter a bug

src/domain/create-entry.spec.ts, src/domain/create-entry.ts
Regressed in https://github.com/bazel-contrib/publish-to-bcr/pull/55
=> fix: fix a bug where an entry failed if the patches dir was missing

src/domain/release-archive.spec.ts, src/domain/release-archive.ts
I was not detecting axios errors properly, so if there was an error in the release archive's url in `source.template.json` (a common error), users would receive an email saying that an unknown error occurred.
Closes https://github.com/bazel-contrib/publish-to-bcr/issues/44
May have clarified https://github.com/bazel-contrib/publish-to-bcr/issues/60
=> fix: friendly errors when the release archive can't be downloaded

package.json, src/application/notifications.ts, src/application/release-event-handler.ts, src/application/webhook/app.module.ts, src/application/webhook/index.ts, src/application/webhook/main.ts, src/application/webhook/providers.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/find-registry-fork.ts, src/domain/publish-entry.ts, src/domain/repository.spec.ts, src/domain/repository.ts, src/domain/ruleset-repository.spec.ts, src/infrastructure/email.ts, src/infrastructure/git.ts, src/infrastructure/github.ts, src/infrastructure/secrets.ts, tsconfig.json, yarn.lock
Use NestJS to do dependency injection. This is a prefactor I wanted to get in before we make a CLI or GitHub action.
=> refactor: use a dependency injection framework

src/domain/publish-entry.spec.ts, src/domain/publish-entry.ts, src/infrastructure/github.ts
Closes https://github.com/bazel-contrib/publish-to-bcr/issues/187.
=> feat: enable auto-merge on BCR pull requests

package.json
Not needed now that we build with bazel.
=> chore: remove old npm scripts

package.json, pnpm-lock.yaml, src/application/cli/BUILD.bazel, src/application/cli/create-entry-command.ts, src/application/notifications.ts, src/application/release-event-handler.ts, src/application/webhook/main.ts, src/domain/create-entry.ts, src/domain/metadata-file.ts, src/domain/publish-entry.ts, src/domain/release-archive.spec.ts, src/domain/release-archive.ts, src/domain/ruleset-repository.ts, src/domain/source-template.spec.ts, src/domain/source-template.ts
Add logging for the CLI and helpful error handling.
Stacked on top of https://github.com/bazel-contrib/publish-to-bcr/pull/231.
=> feat(cli): improve error messages and logging

MODULE.bazel, e2e/cli/BUILD.bazel, e2e/cli/e2e.bats, src/application/cli/BUILD.bazel, src/application/cli/main.ts, src/domain/release-archive.ts
Stacked on top of https://github.com/bazel-contrib/publish-to-bcr/pull/233
=> test: add e2e tests for cli

.gitattributes, MODULE.bazel, dist/cli/BUILD.bazel, e2e/cli/BUILD.bazel, e2e/cli/e2e.bats, package.json, pnpm-lock.yaml, src/application/cli/BUILD.bazel, src/application/cli/cjs-shim.js
This is in preparation for creating a GitHub Actions custom javascript action which requires all dependencies to exist in the source repo.
fyi @loosebazooka
=> feat: bundle and vendor cli

.github/workflows/action-e2e.yaml, MODULE.bazel, action.yaml, e2e/cli/BUILD.bazel, e2e/cli/e2e.bats, package.json, pnpm-lock.yaml, src/application/action/BUILD.bazel, src/application/action/attest.ts, src/application/action/main.ts, src/application/cli/BUILD.bazel, src/application/cli/create-entry-command.ts
Create GitHub Actions attestations for MODULE.bazel and source.json using the action. This does not yet include templating and including attestations.json in the entry, which is an orthogonal concern. The attestations are created in a directory outside of the entry because we never want to commit them to the BCR and we need some place to output them.
=> feat: attest generated bcr files

e2e/cli/e2e.bats, e2e/fixtures/attestations/.bcr/attestations.template.json, e2e/github-webhook/__snapshots__/e2e.spec.js.snap
Follow the format outlined in https://github.com/bazelbuild/bazel-central-registry/pull/3924.
=> fix: fix attestations.json file in test fixture

.github/workflows/action-e2e.yaml, e2e/action/setup-test-fixture.sh, e2e/cli/BUILD.bazel, e2e/cli/e2e.bats, e2e/fixtures/multi-module/README.md, e2e/github-webhook/__snapshots__/e2e.spec.js.snap, src/application/action/attest.ts, src/application/action/main.ts, src/application/cli/create-entry-command.ts, src/domain/configuration.spec.ts, src/domain/configuration.ts, src/domain/ruleset-repository.spec.ts, src/domain/ruleset-repository.ts
Support multi-module same-version publishing for the CLI and the GitHub Action.
Example CLI output:
```
Publish to BCR
Loaded configuration from /home/derek/Code/publish-to-bcr-fixtures/fixture-multi-module/.bcr/config.yml
Detected multiple module roots: [".","sub/module"]
Loading template files from /home/derek/Code/publish-to-bcr-fixtures/fixture-multi-module/.bcr
Creating entry for module version 0.0.10 in /home/derek/Code/bazel-central-registry
Fetching release archive https://github.com/publish-to-bcr-dev/fixture-multi-module/releases/download/v0.0.10/fixture-multi-module-root-v0.0.10.tar.gz
The release archive's MODULE.bazel version 0.0.0 does not match release version 0.0.10. Creating a version patch.
Successfully created entry for fixture-multi-module-root@0.0.10
Loading template …
```
=> feat(cli/action): publish multiple module entries

src/application/cli/app.module.ts, src/application/cli/providers.ts, src/application/cli/yargs.spec.ts, src/application/webhook/app.module.ts, src/application/webhook/providers.ts, src/domain/artifact.spec.ts, src/domain/artifact.ts, src/domain/attestations-template.spec.ts, src/domain/attestations-template.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/release-archive.spec.ts, src/domain/release-archive.ts
Closes https://github.com/bazel-contrib/publish-to-bcr/issues/256.
=> fix: use different download retry delays for app and cli

README.md, templates/README.md
Now that we've shipped the first BCR module that uses it.
=> feat: document the new re-usable workflow
