src/application/notifications.ts, src/application/release-event-handler.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/error.ts, src/domain/find-registry-fork.spec.ts, src/domain/find-registry-fork.ts, src/domain/ruleset-repository.spec.ts, src/domain/ruleset-repository.ts, src/test/mock-template-files.ts
I decided not to send success notifications. Any GitHub user who wants to be notified of things probably has a notification for being tagged in a PR, which they will be for the BCR PR.
I did a first pass on error messages to include in the email. I'll have another set of errors to add for issues when creating the entry and stamping files, but I'll do that in another PR.
=> feat: send more helpful error notifications

src/application/notifications.ts, src/application/release-event-handler.ts, src/domain/publish-entry.spec.ts, src/domain/publish-entry.ts, src/infrastructure/github.ts
Previously I was indirectly notifying the releaser by tagging them as a reviewer on the pull request. While this works for us, it will fail for most users because they are not collaborators on `bazelbuild/bazel-central-registry`.
Instead, I'm tagging their user name in the PR body so they get a mention ~and sending a success email with a link to the PR~.
=>   feat: tag releaser in pull request instead of requesting review 

src/application/release-event-handler.ts, src/domain/config.ts, src/domain/ruleset-repository.spec.ts, src/domain/ruleset-repository.ts, src/test/mock-template-files.ts, templates/README.md
Addresses: https://github.com/bazel-contrib/publish-to-bcr/issues/17
This changes the fixed releaser schema to:
```
fixedReleaser:
login: <USER>
email: <EMAIL>
```
Unless we add more permissions to the app, a user's email can't be fetched unless it's publicly visible on their profile. The result is that the commit on BCR doesn't have an email and could cause some tracking issues for stats in the future.
This adds a way to ensure an email gets set.
This is a breaking API change. However, since Aspect and @fmeum are the only ones using this, we can make the change safely.
=> feat: set login/email on fixed releaser

src/domain/release-archive.spec.ts, src/domain/release-archive.ts
This is a better solution than https://github.com/bazel-contrib/publish-to-bcr/pull/30
Bazel already seems to handle the `.` prefix inside of a tarball without needing a `strip_prefix` in `http_archive`. We shouldn't need ruleset authors to add this to their `source.json` file in bcr entries.
This PR fixes the issue by not trying to extract only `MODULE.bazel` from a release tarball, which required the prepended `"./" on the extraction path. Instead, extract the whole archive (like we do for zips) and let the filesystem cancel out the leading ".".
=> fix: fix a bug where tarballs with a '.' prefix were not extracted correctly

src/application/release-event-handler.ts, src/domain/ruleset-repository.spec.ts, src/domain/ruleset-repository.ts, src/domain/source-template.ts, src/domain/user.ts
Addresses https://github.com/bazel-contrib/publish-to-bcr/issues/32.
The issue was I wasn't setting a releaser before validating the ruleset template files so there was no one to send an email to. If there was an error validating the ruleset template files, it will still try to look for the `fixedReleaser` in the configuration file.
=> fix: fix a bug where releasers were not notified of template errors

src/domain/source-template.spec.ts, src/domain/source-template.ts
Addresses the error in https://github.com/bazel-contrib/publish-to-bcr/issues/32
fyi @fmeum for rules_go
=> fix: make strip_prefix optional in the source template

src/domain/ruleset-repository.spec.ts, src/domain/ruleset-repository.ts, src/test/mock-template-files.ts
This is especially bad because an empty config file is in the default template folder that people copy over :scream_cat:
=> fix: fix a bug where an empty config file threw

src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/test/mock-template-files.ts
Fixes: https://github.com/bazel-contrib/publish-to-bcr/issues/35
fyi: @fmeum
=> fix: preserve yanked_versions in bcr metadata

src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/find-registry-fork.spec.ts, src/domain/find-registry-fork.ts, src/infrastructure/github.ts
Currently we find candidate BCR forks to push to, then try the whole workflow in a loop. There's no point even attempting to publish an entry to a fork that doesn't have the app installed to it. Detect this earlier and improve the email we send to users. Forgetting to install the app to a fork is the most common issue new users have.
=> refactor: detect missing app installations on fork earlier

src/domain/repository.spec.ts, src/domain/repository.ts, src/infrastructure/git.ts
Reverts bazel-contrib/publish-to-bcr#42
This caused a couple of releases to fail.
Apparently you can't push from shallow clones: https://stackoverflow.com/a/28985327, so it failed when pushing a branch to the bcr fork.
=> Revert "refactor: avoid downloading entire repository histories"

package.json, src/domain/release-archive.spec.ts, src/domain/release-archive.ts, yarn.lock
Replace the archive downloader with axios and an axios retry plugin. Also add a friendly error message so that users will be notified the download failed (rather than receiving an unknown failure email).
This is useful for those who publish a release artifact shortly after the release itself is published causing a race condition. It also makes the app robust to random GitHub download failures, which I've seen happen a couple of times.
=> feat: retry archive downloads

README.md, src/application/release-event-handler.ts, src/domain/config.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/publish-entry.spec.ts, src/domain/publish-entry.ts, src/domain/release-archive.spec.ts, src/domain/release-archive.ts, src/domain/ruleset-repository.spec.ts, src/domain/ruleset-repository.ts, src/infrastructure/git.ts, templates/README.md
Addresses #46 
This is to support rules_python and skylib publishing multiple modules on a release.
Examples of PRs created for rules_python fork:
https://github.com/publish-to-bcr-dev-registry/bazel-central-registry/pull/53
https://github.com/publish-to-bcr-dev-registry/bazel-central-registry/pull/54
=> feat: support publishing multiple modules per repo

README.md, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/ruleset-repository.spec.ts, src/domain/ruleset-repository.ts
Fixes https://github.com/bazel-contrib/publish-to-bcr/issues/49.
Allows arbitrary patches to be added to BCR releases. All patches must have the same strip prefix, so standardizing on `-p1`.
=> feat: add patches to bcr entries

src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/module-file.spec.ts, src/domain/module-file.ts, src/test/mock-template-files.ts
If an included patch patches MODULE.bazel, then it needs to be applied to the copy of MODULE.bazel in the bcr entry because it must be identical to the extracted-and-patched version.
Closes https://github.com/bazel-contrib/publish-to-bcr/issues/57.
Example entry: https://github.com/publish-to-bcr-dev-registry/bazel-central-registry/pull/63/files
=> fix: apply patches to entry module file

deployment/modules/webhook/main.tf
A ruleset release crashed the cloud function because it ran out of memory. Increase to 512MB.
=> fix: increase ram

package.json, src/domain/create-entry.spec.ts, src/domain/find-registry-fork.spec.ts, src/domain/integrity-hash.spec.ts, src/domain/module-file.spec.ts, src/domain/publish-entry.spec.ts, src/domain/release-archive.spec.ts, src/domain/repository.spec.ts, src/domain/ruleset-repository.spec.ts, src/domain/source-template.spec.ts, src/test/util.ts, tsconfig.json, yarn.lock
Prefactor for #75 
In the above PR I want to add a custom jest matcher, however using `@jest/globals` doesn't seem to work when defining types for custom matchers:
https://github.com/testing-library/jest-native/issues/136
https://github.com/jestjs/jest/issues/10642
I was able to get the matcher type definitions working by instead using `@types/jest` and declaring the types as global in tsconfig.json.
=> chore: remove @jest/globals and use global types in tests

jest.setup.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/metadata-file.spec.ts, src/domain/metadata-file.ts, src/domain/ruleset-repository.ts
Prefactor for #75 
Depends on  #76 
Richly models the bcr metadata file so that it's easier to pull out the maintainers.
=> refactor: richly model metadata file

src/application/release-event-handler.ts, src/domain/publish-entry.spec.ts, src/domain/publish-entry.ts
Prefactor for #75 
Depends on #76
=> feat: include release url in pr body

src/application/cloudfunction/github-webhook-entrypoint.ts, src/application/notifications.ts, src/application/release-event-handler.ts, src/domain/metadata-file.spec.ts, src/domain/metadata-file.ts, src/domain/publish-entry.spec.ts, src/domain/publish-entry.ts, src/domain/ruleset-repository.ts, src/infrastructure/email.ts, templates/.bcr/metadata.template.json, templates/README.md
It's common for a new user's first publish to fail and they receive no notification. This happens when they use release automation and the release author is the github-actions bot, so we can't attribute the release event to a user with an email.
This improves the chances that someone will receive an email by emailing errors to everyone in the maintainers list in the bcr entry's metadata.json file. It also makes maintainers aware of releases by tagging them in the PR body.
Related to https://github.com/bazel-contrib/publish-to-bcr/issues/59
=> feat: notify maintainers of releases and issues

.github/workflows/ci.yaml, deployment/modules/webhook/main.tf, package.json
Google Cloud Functions is deprecating node16 support in January.
=> chore: upgrade to node18 runtime

src/application/release-event-handler.ts
Caused by some recent refactoring. This was returning undefined and the error handling code puked when it tried to read the object.
=> fix: fix a bug where a ruleset error results in an unknown error

src/infrastructure/github.ts
This reverts commit 354ba4e07b1bc75ebebcc7bb1103ab187f5b9753.
Recall there are actually two GitHub apps: one that users install to their ruleset/fork, and one that Google installs on the BCR for opening pull requests. The second app doesn't have repository write permissions so Google is more comfortable installing it to the BCR.
Testing this in my dev environment, it fails because the second GitHub app, which opens up the pull request, doesn't have permissions to the fork it's pr'ing from, so it can't enable this option. To solve this, I think we would need to ask users to install both apps (worse DX) or use one app with elevated permissions (Google doesn't like).
=> Revert "feat: allow BCR maintainers to modify pull request"

src/domain/metadata-file.spec.ts, src/domain/metadata-file.ts
The issue was that `validSemver` defaults loose parsing while `semverCompare` defaults to strict parsing. The comparison method was being passed an invalid semver and threw.
Closes https://github.com/bazel-contrib/publish-to-bcr/issues/97.
=> fix: be consistently strict when parsing semvers

e2e/stubs/cloud-functions.ts, src/infrastructure/secrets.ts
This regressed [here](https://github.com/bazel-contrib/publish-to-bcr/pull/102/files#diff-ea429e183d271a16af993f4c620905c6d071c4062ba83288bbe1b91b2a41a480R21-L21). I had read some outdated docs that said the project id was exposed as an environment variable, but this is only true for older runtimes.
=> fix: correctly fetch gcp project id

e2e/e2e.spec.ts, e2e/helpers/fixture.ts, e2e/stubs/fake-github.ts, src/infrastructure/github.ts
When the release author is the `github-actions[bot]` and a fixedReleaser isn't set, the author of the commit in the BCR PR doesn't render well. Example: https://github.com/bazelbuild/bazel-central-registry/pull/1195/commits/051881937d9d730082bfb18357522d791968d746.
The properly sets the correct author info for the bot for GitHub to render it correctly.
Closes https://github.com/bazel-contrib/publish-to-bcr/issues/82.
=> fix: properly attribute the github-actions[bot] as a commit author

.github/workflows/ci.yaml
E2es fail on pull requests from a fork because GitHub Actions doesn't allow access to secrets on the `pull_request` trigger. `pull_request_target ` is supposed to allow this. I added the label `run e2e` to tag PRs to allow e2es to be run, the assumption being that we carefully look through the changes before tagging. In addition, outside contributions must be approved.
=> ci: don't run e2es on PRs from forks

templates/.bcr/source.template.json, templates/README.md
BCR appears to enforce this now
=> Update template URL to a stable URL

e2e/e2e.spec.ts, e2e/helpers/webhook.ts, e2e/stubs/fake-github.ts, src/application/cloudfunction/github-webhook-entrypoint.ts, src/application/octokit.ts, src/application/release-event-handler.ts, src/domain/create-entry.spec.ts, src/domain/find-registry-fork.spec.ts, src/domain/publish-entry.spec.ts, src/infrastructure/github.ts
Prefactor for #120.
I had an awkward coupling between how the github client (octokit) is authorized and the api calls it can make, when really they should be separate. There are several different ways we need to authorize: as one of the two GitHub apps, as an installation of those apps on the ruleset repo, bcr fork, and canonical bcr. This decoupling will help me fix #120 in a clean way.
=> refactor: decouple github auth from api calls

README.md, e2e/e2e.spec.ts, e2e/stubs/fake-github.ts, src/application/release-event-handler.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/user.ts, src/infrastructure/github.ts
When the release author is the `github-actions` bot, attribute the entry commit to the `publish-to-bcr-bot` to avoid CLA issues on the BCR. The bot has already "signed" the CLI in order to open up the PRs.
Closes #120
=> feat: use app bot as commit author in place of github-actions bot

e2e/__snapshots__/e2e.spec.ts.snap, e2e/e2e.spec.ts, e2e/fixtures/unversioned/MODULE.bazel, e2e/fixtures/unversioned/README.md, e2e/fixtures/zero-versioned/.bcr/metadata.template.json, e2e/fixtures/zero-versioned/.bcr/presubmit.yml, e2e/fixtures/zero-versioned/.bcr/source.template.json, e2e/fixtures/zero-versioned/MODULE.bazel, e2e/fixtures/zero-versioned/README.md, e2e/helpers/fixture.ts, src/domain/create-entry.ts, src/domain/module-file.spec.ts, src/domain/module-file.ts
Fixes https://github.com/bazel-contrib/publish-to-bcr/issues/95
The `version` attribute is technically [required](https://bazel.build/rules/lib/globals/module#module) for non-root modules, but it should be ok for repos to not have it if they use the publish-to-bcr-bot to automatically patch it in when publishing to BCR.
=> Cope with missing `version` attribute on module

e2e/__snapshots__/e2e.spec.ts.snap, e2e/e2e.spec.ts, e2e/fixtures/multi-module/.bcr/source.template.json, e2e/helpers/email.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/release-archive.spec.ts, src/domain/release-archive.ts
This is one of the most common failures for first time releases, but a generic "something went wrong" email was sent
Closes #83
=> feat: send helpful email when strip prefix is incorrect

src/domain/metadata-file.spec.ts, src/domain/version.spec.ts, src/domain/version.ts
Closes https://github.com/bazel-contrib/publish-to-bcr/issues/152.
=> fix: correctly sort bazel version string components that begin with digts

e2e/__snapshots__/e2e.spec.ts.snap, e2e/fixtures/empty-prefix/.bcr/presubmit.yml, e2e/fixtures/fixed-releaser/.bcr/presubmit.yml, e2e/fixtures/multi-module/.bcr/presubmit.yml, e2e/fixtures/multi-module/.bcr/submodule/presubmit.yml, e2e/fixtures/no-prefix/.bcr/presubmit.yml, e2e/fixtures/tarball/.bcr/presubmit.yml, e2e/fixtures/unversioned/.bcr/presubmit.yml, e2e/fixtures/versioned/.bcr/presubmit.yml, e2e/fixtures/zero-versioned/.bcr/presubmit.yml, e2e/fixtures/zip/.bcr/presubmit.yml, templates/.bcr/presubmit.yml, templates/README.md
The bazel version is now required in BCR presubmit files.
Closes https://github.com/bazel-contrib/publish-to-bcr/issues/150.
=> docs: update presubmit example to include bazel version

README.md, e2e/e2e.spec.ts, src/application/release-event-handler.ts, src/domain/publish-entry.spec.ts, src/domain/publish-entry.ts, templates/README.md
The Bazel Central Registry now has a bot that tags maintainers in a comment prompting them to review the PR. This makes the mentions in the PR body redundant, and additionally causes log spam since the mentions end up in commit messages. Remove all mentions of users from the PR body.
=> feat: stop tagging author and maintainers in pr body

package.json, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, yarn.lock
Add retries with exponential backoff to the push to the BCR fork. Occasionally GitHub randomly errors out on the push causing an entry to fail to be created.
Part of https://github.com/bazel-contrib/publish-to-bcr/issues/94
=> feat: make git pushes more robust

src/application/release-event-handler.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/ruleset-repository.ts
Read the module name from the release archive rather than the ruleset repo when opening a pull request. A MODULE.bazel file should not be required to be present in the repo.
=> fix: don't assume MODULE.bazel file in ruleset repo

deployment/modules/webhook/main.tf
The cloud function was running out of memory when processing releases for some repositories, including [protobuf](https://github.com/bazel-contrib/publish-to-bcr/issues/165).
=> chore: increase memory limit to 1024mb

src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/repository.spec.ts, src/domain/repository.ts, src/domain/ruleset-repository.spec.ts, src/domain/ruleset-repository.ts, src/infrastructure/git.ts
Publish to BCR gets memory spikes for certain repositories such as protobuf. Perform shallow clones on the ruleset repository (only the release tag) and the bazel-central-registry (main) to see if this helps.
Related to https://github.com/bazel-contrib/publish-to-bcr/issues/165
=> chore: shallow clone repositories

README.md, e2e/__snapshots__/e2e.spec.ts.snap, e2e/e2e.spec.ts, e2e/fixtures/multi-module/.bcr/submodule/metadata.template.json, src/application/notifications.ts, src/application/release-event-handler.ts, src/domain/publish-entry.spec.ts, src/domain/publish-entry.ts, src/domain/ruleset-repository.ts
Publish multiple modules in the same pull request in case one depends on the other.
Closes https://github.com/bazel-contrib/publish-to-bcr/issues/164 
fyi: @wyverald
=> feat: publish multiple modules in the same pr

e2e/e2e.spec.ts, jest.setup.ts, src/domain/release-archive.spec.ts, src/domain/release-archive.ts
=> Give release archive workflows more time

src/domain/release-archive.spec.ts, src/domain/release-archive.ts
Follow-up to #170. I suppose this is what we get for unit-testing but not e2e-testing. On the other hand, I don't have the means to e2e-test this myself, so this is the best I can do right now.
=> Retry on HTTP 404

e2e/__snapshots__/e2e.spec.ts.snap, src/domain/module-file.spec.ts, src/domain/module-file.ts
A `module` directive with `version = ""` resulted in the version being stamped into the first `bazel_dep`.
Also fix the indentation to follow `buildifier`'s style.
=> fix: recognize explicitly empty version strings

e2e/__snapshots__/e2e.spec.ts.snap
The test code that produces the zip doesn't produce the same output on all platforms. Until that's fixed, update to what passes on CI.
=> fix: integrity in snapshot test

src/domain/release-archive.ts, src/infrastructure/xzdec/xzdec.ts
Wait for the writable stream to end before reading the extracted module file. Also pause subsequent writes while the write buffer needs to be drained. It's not clear why the latter is necessary as the [docs](https://nodejs.org/api/stream.html#writablewritechunk-encoding-callback) suggest you can continue to do writes while undrained content continues to be buffered in memory. However, this seems to fix an issue where the extracted content was incorrect.
Example of a working publish on the dev environment: https://github.com/publish-to-bcr-dev-registry/bazel-central-registry/pull/82.
Closes https://github.com/bazel-contrib/publish-to-bcr/issues/176.
=> fix: xz decompression issues

package.json
This must be new because I haven't run into this before, but deploying a cloud function runs the `build` script in package.json. This will fail on cloud run because the build script relies on local scripts that we don't publish. We have no need for building on cloud run since we upload an already built artifact.
=> fix: don't run build script on cloud function deploy

.npmrc
Pnpm disables these scripts by default.
=> fix: fix prebuild script not executing after pnpm migration

e2e/e2e.spec.ts, e2e/stubs/fake-github.ts
Test coverage for auto merge feature added in https://github.com/bazel-contrib/publish-to-bcr/commit/9c412816bc7a9389e4bb626673ecce25416f9ba9.
=> test: add coverage for auto merge feature

e2e/e2e.spec.ts, src/application/notifications.ts, src/application/release-event-handler.ts, src/application/webhook/app.module.ts, src/application/webhook/providers.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/find-registry-fork.spec.ts, src/domain/find-registry-fork.ts, src/domain/publish-entry.spec.ts, src/domain/publish-entry.ts, src/domain/repository.ts, src/domain/user.ts, src/infrastructure/github.ts
Remove references from the `domain` layer out of the `infrastructure` layer. This caused circular dependencies when converting this repo to build with bazel.
=> refactor: fix a layer violation causing a circular dependency

.github/workflows/ci.yaml, package.json, pnpm-lock.yaml
I decided to upgrade pnpm for no particular reason in this [commit](https://github.com/bazel-contrib/publish-to-bcr/commit/8700220459d5e2ba8e11c9e13c3a87c140c7c982#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R8). Deploying the cloud function failed when using a pnpm 9 lockfile failed with this error:
```
 ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation. The current "pnpmfileChecksum" configuration doesn't match the value found in the lockfile
```
Potentially related issues:
* https://github.com/pnpm/pnpm/issues/6824
* https://github.com/pnpm/pnpm/issues/7951
Google has no documentation on what versions of pnpm it supports. Downgrading seemed to fix the issue, so I'm just going to go with that for now.
=> fix: downgrade pnpm to v8

.github/workflows/ci.yaml, package.json, pnpm-lock.yaml, src/infrastructure/secrets.ts
In integration tests the google node client  would fail unless it could load some default credentials, even though the secrets endpoint is stubbed and the credentials are not actually used. My previous solution was to add some credentials as a secret which prevented e2e tests from running on fork builds.
I found a simpler way to mock the auth client removing the need for any secrets.
This is also a prefactor for running the e2e tests under bazel, which can't find default credentials on the home directory when run in the sandbox.
=> refactor: remove fake google credentials

src/application/release-event-handler.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/publish-entry.spec.ts, src/domain/publish-entry.ts
Move the "commit entry" and "push to fork" logic out of the `CreateEntryService` into the `PublishEntryService`. This isolates the entry file creation domain logic so that it's easier to inject and reuse in the CLI.
=> refactor: move push logic out of create entry service

src/application/cli/BUILD.bazel, src/application/cli/create-entry-command.ts, src/application/cli/yargs.spec.ts, src/application/cli/yargs.ts, src/domain/BUILD.bazel, src/domain/config.ts, src/domain/configuration.spec.ts, src/domain/configuration.ts, src/domain/ruleset-repository.spec.ts, src/domain/ruleset-repository.ts, src/test/mock-template-files.ts
Load the configuration file in the create entry CLI command. This involves some refactoring of the configuration loading logic out of the RulesetRepository class.
The CLI now takes a `--templates-dir` option rather than a `--ruleset-repo` option. Unlike the app, which needs to know the ruleset repository to clone and checkout to view the files under `.bcr`, the CLI will either be executed inside of an action, where the repo is presumably checked out, or locally, where a release would also have a local checkout. There's no need for the CLI to perform the clone.
Ideally the CLI wouldn't depend on a `.bcr` directory structure, which was added for the app specifically to be able to find template files, but for now that's the easiest migration path. In the future I could add additional args …
=> feat(cli): load configuration

src/application/cli/BUILD.bazel, src/application/cli/app.module.ts, src/application/cli/create-entry-command.ts, src/application/cli/yargs.spec.ts, src/application/cli/yargs.ts, src/application/release-event-handler.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/repository.spec.ts, src/domain/repository.ts, src/domain/source-template.spec.ts, src/domain/source-template.ts, tsconfig.json
This creates a new set of entry files for a module release in a locally checked out registry. In addition:
- Refactored the `CreateEntryService` to work for both the app and the cli
- No longer loading the config file for the cli as the only options in there are only needed by the app
- Multi-module entries are already supported by running the cli multiple times and changing the `--templates-dir`
=> feat(cli): create bcr entry from command

src/application/cli/create-entry-command.ts, src/application/release-event-handler.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/ruleset-repository.ts, src/domain/source-template.spec.ts, src/domain/source-template.ts
This catches an error case where some variables don't have substitutions in the source template file. It's intended for the CLI as the GitHub app always has all information needed for substitutions. The handling of the error and messaging (as well as for other errors) will be in a follow-up PR.
Prefactor for https://github.com/bazel-contrib/publish-to-bcr/pull/230.
=> feat: detect unsubstituted vars in source template

src/domain/BUILD.bazel, src/domain/artifact.spec.ts, src/domain/artifact.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/release-archive.spec.ts, src/domain/release-archive.ts
An artifact is some remote file that gets downloaded and has its integrity hash computed.
Prefactor for https://github.com/bazel-contrib/publish-to-bcr/pull/239 where attestation artifacts need to be downloaded.
=> refactor: model release artifacts

src/application/cli/create-entry-command.ts, src/domain/BUILD.bazel, src/domain/source-template.ts, src/domain/substitution.spec.ts, src/domain/substitution.ts
Move some template substitution logic outside of the source template class so it can be reused for the attestations template.
Prefactor for https://github.com/bazel-contrib/publish-to-bcr/pull/239.
=> refactor: move substitution out of source template

e2e/cli/BUILD.bazel, e2e/cli/e2e.bats, e2e/fixtures/BUILD.bazel, e2e/fixtures/attestations/.bcr/attestations.template.json, e2e/fixtures/attestations/.bcr/metadata.template.json, e2e/fixtures/attestations/.bcr/presubmit.yml, e2e/fixtures/attestations/.bcr/source.template.json, e2e/fixtures/attestations/MODULE.bazel, e2e/fixtures/attestations/README.md, e2e/github-webhook/BUILD.bazel, e2e/github-webhook/__snapshots__/e2e.spec.js.snap, e2e/github-webhook/e2e.spec.ts, e2e/github-webhook/helpers/fixture.ts, e2e/github-webhook/stubs/fake-github.ts, src/application/cli/create-entry-command.ts, src/application/release-event-handler.ts, src/domain/BUILD.bazel, src/domain/attestations-template.spec.ts, src/domain/attestations-template.ts, src/domain/create-entry.spec.ts, src/domain/create-entry.ts, src/domain/publish-entry.ts, src/domain/ruleset-repository.ts, src/domain/substitution.ts, src/test/mock-template-files.ts
Generate `attestations.json` from an optional template. Substitute variables and calculate integrity hashes.
Prefactors:
* https://github.com/bazel-contrib/publish-to-bcr/pull/240
* https://github.com/bazel-contrib/publish-to-bcr/pull/241
=> feat: add an attestations.json substitutable template

MODULE.bazel, babel.config.json, bazel/jest/defs.bzl, e2e/cli/e2e.bats, e2e/fixtures/BUILD.bazel, e2e/fixtures/fixture.bzl, e2e/fixtures/tarball-xz/.bcr/metadata.template.json, e2e/fixtures/tarball-xz/.bcr/presubmit.yml, e2e/fixtures/tarball-xz/.bcr/source.template.json, e2e/fixtures/tarball-xz/MODULE.bazel, e2e/fixtures/tarball-xz/README.md, e2e/github-webhook/BUILD.bazel, e2e/github-webhook/__snapshots__/e2e.spec.js.snap, e2e/github-webhook/e2e.spec.ts, e2e/github-webhook/helpers/fixture.ts, package.json, pnpm-lock.yaml, src/infrastructure/xzdec/xzdec.ts
Now that the repository has converted to bazel, we can bring in `rules_xz` to prepare a compressed xz fixture to test.
=> test: add an integration test for xz decompression

.github/workflows/action-e2e.yaml, action.yaml, src/application/action/main.ts
The module name output is needed by the reusable workflow to include the module name in the created PR title. Note that the module name is not known until the action runs because it's extracted from the MODULE.bazel file in the release archive.
=> feat(action): add module name output

src/domain/artifact.spec.ts, src/domain/artifact.ts
Experimentally, I found the current delay factor causes a full retry sequence to take about 2m30s which seems long both for the CLI and for the GitHub app. Tweak the factor to take about 30s and output the retry attempts.
```
Publish to BCR
Loading template files from /home/derek/Code/bazel-lib/.bcr
Creating entry for module version 3.0.0 in /home/derek/Code/bazel-central-registry
Fetching release archive https://github.com/bazel-contrib/bazel-lib/releases/download/v3.0.0/bazel-lib-v3.0.0.tar.gz
Failed to download artifact; Request failed with status code 404
Retry atempt 1 / 3...
Failed to download artifact; Request failed with status code 404
Retry atempt 2 / 3...
Failed to download artifact; Request failed with status code 404
Retry atempt 3 / 3...
Failed to download release archive …
```
=> fix: tweak the delay factor when downloading artifacts

templates/README.md
Related to https://github.com/bazelbuild/bazel-central-registry/pull/4191.
=> docs: instruct users to add a github_user_id to maintainers list

.github/workflows/publish.yaml
In https://github.com/bazelbuild/bazel-central-registry/pull/4324, everything has seemingly succeeded, but the publish-to-bcr job in my repo got marked as failed because of this error.
```console
Run gh pr merge -R "bazelbuild/bazel-central-registry" --squash --auto "4324"
shell: /usr/bin/bash -e {0}
env:
VERSION: 1.0.157
GH_TOKEN: ***
GraphQL: dtolnay does not have the correct permissions to execute `EnablePullRequestAutoMerge` (enablePullRequestAutoMerge)
Error: Process completed with exit code 1.
```
https://github.com/dtolnay/cxx/actions/runs/14463112632/job/40559600788
=> fix: disregard 'gh pr merge' permission error

.github/workflows/publish.yaml
I suspect some people will want to switch to the reusable workflow for publishing before they start using the new release workflow or produce attestations themselves. Currently the workflow relies on attestations being produced for the release archive. For a time while the BCR does not require attestations, allow the publish to turn this part off. When attestations are required by the BCR, we will remove this property. This way the workflow can be used as a drop-in replacement for the app.
Tested a [publish](https://github.com/publish-to-bcr-dev/fixture-versioned/actions/runs/14480806504/job/40617160317_)/[pr](https://github.com/fweikert/bazel-central-registry/pull/18/files)
=> feat: make attestations optional in reusable publish workflow

templates/.bcr/presubmit.yml
- New users should also find Bazel 8 in their template
- Bump Ubuntu and Debian images to more recent versions. Ubuntu 2004 is about to EOL in the next weeks.
=> Add bazel 8 and bump platforms in presubmit template

.github/workflows/publish.yaml
Most users will fall into the category "doesn't have merge permission on the registry repository". And, BCR has its own automation via @bazel-io bot to merge PRs that have needed approvals, regardless of the auto-merge setting.
=> fix(publish): don't try to set auto-merge

.github/workflows/action-e2e.yaml, src/application/action/main.ts
All PRs are publishes so adding it is redundant. Only include the module name(s) and vesion.
=> feat(workflow): don't include 'Publish' in the pr title

.github/workflows/publish.yaml
Marking a PR as "Ready" is one mechanism the BCR can use to allow PR authors to self approve new entries.
Related to https://github.com/bazel-contrib/publish-to-bcr/issues/261.
Tested [here](https://github.com/fweikert/bazel-central-registry/pull/20).
=> feat(workflow): open prs in draft mode

.github/workflows/release.yaml
Generate release notes when tagging a release. This will let the reusable workflows users know what changed between releases. In the future, I may publish CLI binaries, but I'm not sure if that will be useful if attestations become necessary.
A follow-up will be to find a way to make this `release` job wait for the buildkite build.
Closes https://github.com/bazel-contrib/publish-to-bcr/issues/265.
=> chore: generate release notes

templates/README.md
Address https://github.com/bazelbuild/bazel-central-registry/pull/4589#issuecomment-2881249881
=> Correctly indicate `github_user_id` as a number

.github/workflows/publish.yaml
Separate the actions for pushing an entry to a fork and opening a pull request. This is a prefactor for partial support of fine-grained access tokens, where the "Create pull request" step will be made optional.
Part of https://github.com/bazel-contrib/publish-to-bcr/issues/271.
Successful run [example](https://github.com/publish-to-bcr-dev/fixture-versioned/actions/runs/15119817123/job/42499386523).
=> refactor(workflow): separate push and pull

.github/workflows/publish.yaml, README.md
Add an option to skip opening the pull request. This allows fine-grained PATs to be used.
Closes https://github.com/bazel-contrib/publish-to-bcr/issues/271.
Example [run](https://github.com/publish-to-bcr-dev/fixture-versioned/actions/runs/15126832007/job/42520302450).
=> feat(workflow): optionally skip PR creation

.github/workflows/publish.yaml
After I [stopped using](https://github.com/bazel-contrib/publish-to-bcr/commit/ec3df490dbac49c61d87e725d1e6260db8878870) peter-evans/create-pull-request to do the branch push and open PR, we lost some functionality for setting the actor of the workflow to be the commit author. This is necessary to pass the CLA agreement on the BCR.
Tested [here](https://github.com/publish-to-bcr-dev/fixture-versioned/actions/runs/15282248891/job/42983892579).
=> fix(workflow): set github actor as commit author

.github/workflows/publish.yaml
This is not an exhaustive set of fixes for [zizmor](https://github.com/zizmorcore/zizmor) reported issues, just those related to github inputs/vars and template injection
=> Remediate zizmor template injection issues

.github/workflows/publish.yaml
We recently needed to change the `AUTHOR_NAME` and `AUTHOR_EMAIL` with which an internal bot triggers a PR to our BCR fork and therefore the commit that eventually lands to https://github.com/bazelbuild/bazel-central-registry 
It probably makes sense to make these two inputs instead of hardcoded.
=> Add author_{name,email} and committer_{name,email} Inputs

README.md
Closes https://github.com/bazel-contrib/publish-to-bcr/issues/288.
=> docs: link to gh workflow examples in rules template

.github/workflows/publish.yaml
Needed before release for the [docs_url](https://github.com/bazel-contrib/publish-to-bcr/commit/301f65edec7118166379e2ef5f29a05d2868a449) feature.
=> chore: update workflow to point to latest action sha
